package com.example.sabakmrutinim

import androidx.lifecycle.ViewModel

class SacRutiniViewModel: ViewModel() {
    val tumUrunler=listOf(
        Urunler(1,"ogxcoconutmilk", "Ogx Coconut Milk Şampuan", "Saçını Yıka","https://www.trendyol.com/ogx/besleyici-coconut-milk-sulfatsiz-sampuan-385-ml-p-4569859?boutiqueId=61",false,"kuru","pazartesi"),
        Urunler(2,"urbancareargankeratinsackrem", "Urban Care Argan Yağlı Saç Kremi", "Nemlendirici Krem Uygula","https://www.trendyol.com/urban-care/argan-yagi-kolay-kirilan-yipranmis-saclara-ozel-sivi-sac-bakim-kremi-vegan-200-ml-p-733487774?boutiqueId=61",false,"kuru","pazartesi"),
        Urunler(3,"ogxrenewingarganoilofmorocco", "OGX Argan Oil Of Morocco Saç Yağı", "Uçlara Saç Yağı Sür","https://www.trendyol.com/ogx/yenileyici-argan-oil-of-morocco-100-ml-sulfatsiz-sac-bakim-yagi-p-4569875?boutiqueId=61",false,"kuru","pazartesi"),
        Urunler(4,"morfosekeratinhairmask","Morfose Milk Therapy Saç Maskesi","Saçı Nemlendirip Maske Uygula(20 dk) \nHafif Saç Kremi İle Destekle","https://www.trendyol.com/morfose/milk-therapy-sac-maskesi-500-ml-p-32442436?boutiqueId=61",false,"kuru","salı"),
        Urunler(5,"organixhindistanceviziyagi","Wefood Organik Hindistan Cevizi Yağı","Saç Yıkama\nGece Hindistan Cevizi Veya Badem Yağı Sür\nÖr/Bone İle Koru","https://www.trendyol.com/wefood/organik-hindistan-cevizi-yagi-150-ml-soguk-sikim-p-3706799?boutiqueId=61",false,"kuru","çarşamba"),
        Urunler(6,"rosensetatlibademyagi","Cliniva Tatlı Badem Yağı","","https://www.trendyol.com/cliniva/tatli-badem-yagi-100-dogal-soguk-sikim-250ml-yag-p-756036622?boutiqueId=61",false,"kuru","çarşamba"),
        Urunler(7,"herbalessencesarganoilsamp","Herbal Essences Argan Oil Şampuan","Saçını yıka","https://www.trendyol.com/herbal-essences/argan-oil-sac-bakim-sampuani-350ml-p-305120475?boutiqueId=61",false,"kuru","perşembe"),
        Urunler(8,"panteneprovnemterapisikrem","Pantene Nem Terapisi Serum Saç Kremi","Uçlara Saç Kremi sür","https://www.trendyol.com/pantene/miracle-nem-terapisi-serum-sac-bakim-kremi-p-348796908?boutiqueId=61",false,"kuru","perşembe"),
        Urunler(9,"insightdryhairmask","Insight Kuru Saçlar İçin Maske","Nem Maskesi Uygula(20 dk)","https://www.trendyol.com/insight/dry-hair-nourishing-kuru-mat-saclar-icin-besleyici-maske-500-ml-p-3342215?boutiqueId=61",false,"kuru","cuma"),
        Urunler(10,"matsuserum","Matsu Saç Bakım Serumu","Duruladıktan Sonra Serum Uygula","https://www.trendyol.com/matsu/kuru-saclar-icin-yogun-nemlendirici-ve-kopma-karsiti-deep-hydrating-sac-bakim-serumu-50-ml-p-86672291?boutiqueId=61&merchantId=105620",false,"kuru","cuma"),
        Urunler(11,"pantenearganyagi","Pantene Argan Yağı","Yıkama Yok\nUçlara Argan Yağı Sür\nDoğal Şekillendirme(Örgü, Topuz)","https://www.trendyol.com/pantene/dogal-sentez-argan-yagli-elixir-yag-terapisi-100-ml-p-238788?boutiqueId=61",false,"kuru","cumartesi"),
        Urunler(12,"elsevenemlendiricikrem","Elseve Nem Dolduran Saç Bakım Kremi","Şampuanla Yıka\nElma Sirkesi+Su Karışımı İle Saç Derisini Arındır\nNemlendirici Krem+Uçlara Hindistan Cevizi Yağı","https://www.trendyol.com/elseve/hydra-hyaluronic-nem-dolduran-sac-bakim-kremi-250-ml-p-323399057?boutiqueId=61",false,"kuru","pazar"),
        Urunler(13,"glissnemlendiricisampuan","Gliss Nemlendirici Şampuan","Hafif Nemlendirici Şampuan ile Yıka","https://www.trendyol.com/gliss/aqua-revive-nemlendirici-sampuan-normal-ve-kuru-saclar-400-ml-p-846603302?boutiqueId=61&merchantId=117927",false,"normal","pazartesi"),
        Urunler(14,"elsevedreamlongsackremi","Elseve Dream Long Saç Kremi","Uçlara Saç Kremi Sür","https://www.trendyol.com/elseve/l-oreal-paris-l-oreal-paris-dream-long-kolay-tarama-sac-bakim-kremi-p-59274823?boutiqueId=61&merchantId=399971",false,"normal","pazartesi"),
        Urunler(15,"embeautysacmaskesi","Embeauty Saç Maskesi","Saçı Hafif Nemlendir, Besleyici Maske Uygula(15 dk)","https://www.trendyol.com/embeauty/besleyici-onarici-keratin-botoks-etkili-yogun-sac-bakim-maskesi-500-ml-p-871223550?boutiqueId=61&merchantId=1135760",false,"normal","salı"),
        Urunler(16,"elseveserum","Elseve Mucizevi Yağ Sprey Serum","Uçlara Serum Uygula","https://www.trendyol.com/elseve/mucizevi-yag-10-etki-1-arada-sac-guzellestirici-sprey-serum-150ml-p-736256759?boutiqueId=61&merchantId=648413",false,"normal","salı"),
        Urunler(17,"urbancarearganyagi","Urban Care Argan Yağı","Saçı Yıkama\nGerekirse Uçlara Çok Az Bakım Yağı Sür","https://www.trendyol.com/urban-care/argan-yagi-kolay-kirilan-yipranmis-saclara-ozel-sac-bakim-serumu-vegan-75-ml-p-33665464?boutiqueId=61&merchantId=105029",false,"normal","çarşamba"),
        Urunler(18,"pantenemicellarsusampuan","Pantene Micellar Su Şampuan","Saçı Yıka\nHafif Saç Kremi Sür","https://www.trendyol.com/pantene/micellar-sampuan-arindirici-ve-besleyici-p-213153173?boutiqueId=61&merchantId=1082617",false,"normal","perşembe"),
        Urunler(19,"lorealparisonaricibakimspreyi","L'Oreal Paris Onarıcı Bakım Spreyi","Nemlendirici Sprey Kullan","https://www.trendyol.com/l-oreal-paris/professionnel-serie-expert-absolut-repair-onarici-bakim-spreyi-90ml-p-260593457?boutiqueId=61&merchantId=1111907",false,"normal","perşembe"),
        Urunler(20,"elsevesacmaskesi","Elseve Saç Maskesi","Nem Maskesi Uygula\nSaçını Yıka","https://www.trendyol.com/elseve/coconut-precious-oils-pre-bath-nourishing-hair-mask-300-ml-p-797595596?boutiqueId=61",false,"normal","cuma"),
        Urunler(21,"urbancaresacbakimserumu","Urban Care Saç Bakım Serumu","Duruladıktan Sonra Serum Uygula","https://www.trendyol.com/urban-care/expert-no-6-biotin-caffeine-dokulme-karsiti-sac-bakim-serumu-50-ml-vegan-p-902967945?boutiqueId=61&merchantId=105029",false,"normal","cuma"),
        Urunler(22,"toniguysprey","Toni Guy Şekillendirici Sprey","Şaçı Yıkama\nDoğal Şekil Vermek İçin Nemlendirici Sprey Uygula","https://www.trendyol.com/toni-guy/deniz-tuzu-etkili-sekillendirici-sac-spreyi-200-ml-p-65305612?boutiqueId=61&merchantId=151198",false,"normal","cumartesi"),
        Urunler(23,"hccaresampuan","HC Care Şampuan","Hafif Bir Şampuanla Yıka\nElma Sirkesi+Su Karışımı İle Saç Derisini Arındır","https://www.trendyol.com/hc-care/sampuan-normal-ve-kuru-saclar-icin-340-ml-p-139667196?boutiqueId=61&merchantId=110268",false,"normal","pazar"),
        Urunler(24,"pantenesackremi","Pantene Saç Bakım Kremi","Uçlara Hafif Krem","https://www.trendyol.com/pantene/3-minute-miracle-sac-bakim-kremi-nem-terapisi-p-337639604?boutiqueId=61&merchantId=434200",false,"normal","pazar"),
        Urunler(25,"hccareyaglisacsampuan","HC Care Şampuan","Yağ Dengeleyici Şampuanla Saçını Yıka","https://www.trendyol.com/hc-care/sampuan-yagli-saclar-icin-340-ml-p-139670567?boutiqueId=61",false,"yağlı","pazartesi"),
        Urunler(26,"yvesrochersackremi","Yves Rocher Arındırıcı Saç Kremi","Hafif Saç Kremi Kullan(sadece uçlara)","https://www.trendyol.com/yves-rocher/arindirici-sac-kremi-yagli-saclar-pure-detox-vegan-200ml-p-669867061?boutiqueId=61",false,"yağlı","pazartesi"),
        Urunler(27,"yvesrochermaske","Yves Rocher Peeling ve Maske","Saç Derisine Detoks Etkili Maske Uygula","https://www.trendyol.com/yves-rocher/arindirici-2si1-arada-peeling-ve-maske-yagli-saclar-pure-detox-vegan-200ml-p-751567072?boutiqueId=61",false,"yağlı","salı"),
        Urunler(28,"batistekurusampuan","Batiste Kuru Şampuan","Saçı Yıkama\nGün İçinde Yağlı Görünüm Varsa Kuru Şampuan Kullan","https://www.trendyol.com/batiste/kuru-sampuan-original-200-ml-p-1069294?boutiqueId=61",false,"yağlı","çarşamba"),
        Urunler(29,"headandshoulderssampuan","Head & Shoulders Supreme Şampuan","Arındırıcı Şampuanla Saçı Yıka\nElma Sirkesi+Su Karışımı İle Saç Derisini Arındır\nUçlara Hafif Krem Sür","https://www.trendyol.com/head-and-shoulders/head-shoulders-supreme-sampuan-guc-300-ml-p-128492876?boutiqueId=61",false,"yağlı","perşembe"),
        Urunler(30,"lorealpariskilmaskesi","L'Oreal Paris Saf Kil Arındırıcı Maske","Saçını Yıka\nKil Bazlı Maske Uygula(15 dk)","https://www.trendyol.com/l-oreal-paris/saf-kil-arindirici-maske-pure-clay-50-ml-3600523306237-p-65876544?boutiqueId=61",false,"yağlı","cuma"),
        Urunler(31,"syosssacspreyi","Syoss Volume Lift Saç Spreyi ","Saçı Yıkama\nGün İçinde Yağlı Görünümü Önlemek İçin Sprey Uygula","https://www.trendyol.com/syoss/volume-lift-sac-spreyi-400-ml-p-808025057?boutiqueId=61",false,"yağlı","cumartesi"),
        Urunler(32,"elseveyaglanmakarsitisamp","Elseve Yağlanma Karşıtı Şampuan","Saçı Yıka","https://www.trendyol.com/elseve/hydra-hyaluronic-pure-salisilik-asit-iceren-yaglanma-karsiti-arindirici-sampuan-300ml-p-825999857?boutiqueId=61&merchantId=107819",false,"yağlı","pazar"),
        Urunler(33,"aromaticatonik","Aromatica Tea Tree Purifying Tonic","Saç Derisine Nane/Çay Ağacı Özlü Tonik Uygula","https://www.trendyol.com/aromatica/tea-tree-purifying-tonic-cay-agaci-ozlu-arindirici-tonik-p-38793892?boutiqueId=61&merchantId=106303",false,"yağlı","pazar"),
        Urunler(34,"elsevesackrem","Elseve Yağlanma Karşıtı Saç Kremi","Uçlara Nemlendirici Krem Sür","https://www.trendyol.com/elseve/hydra-hyaluronic-pure-salisilik-asit-iceren-yaglanma-karsiti-nemlendirici-sac-kremi-250ml-p-825988279?boutiqueId=61",false,"yağlı","pazar")
    )
    fun getGunlukUrunler(sacTipi: String, gun: String): List<Urunler> {
        return tumUrunler.filter { it.sacTipi == sacTipi && it.gun == gun }
    }
}